# Generated by Django 4.2.20 on 2025-05-10 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_rename_routepoint_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='BoardGame',
        ),
    ]
