# Generated by Django 4.2.20 on 2025-05-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_route_boardgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.IntegerField(),
        ),
    ]
