# Generated by Django 4.2.20 on 2025-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_point_x_alter_point_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='cols',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgame',
            name='rows',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
