# Generated by Django 4.2.20 on 2025-05-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_boardgame_cols_boardgame_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='cols',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rows',
            field=models.IntegerField(default=6),
        ),
    ]
