# Generated by Django 4.2.20 on 2025-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_point_color_alter_boardgame_cols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='auto_save_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
