# Generated by Django 4.2.20 on 2025-05-16 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0008_boardgame_auto_save_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to='gallery.boardgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('player', 'board_game')},
            },
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['route', 'color', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('route', 'x', 'y')},
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('path_data', models.JSONField()),
                ('game_play_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='gallery.gameplaysession')),
            ],
            options={
                'ordering': ['game_play_session', 'color'],
                'unique_together': {('game_play_session', 'color')},
            },
        ),
    ]
